import Head from 'next/head'
import Image from 'next/image'
import BalabobaRadio from '../components/balaboba-radio'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Balaboba radio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BalabobaRadio />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://yandex.ru/lab/yalm"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Yandex Balabola
        </a>
      </footer>
    </div>
  )
}
